version: '3'
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../app:/app
    ports:
      - "3000:3000"
    depends_on:
      - redis
  redis:
    image: redis:6.2
    tmpfs:
      - /tmp